id: P008214
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 13:08:25.990903
source_metadata:
  id: bdr:W30388
  title: འགར་རྩེ་བསྟན་འཛིན་གྱི་གསུང་རྩོམ།
  author: ''
  volumes:
    664da3bf1a8744f08fb14f50ecf7644f:
      image_group_id: I1KG10349
      title: ''
      volume_number: 1
      total_pages: 384
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
