id: P008214
initial_creation_type: ocr
source_metadata:
  id: bdr:W30388
  title: འགར་རྩེ་བསྟན་འཛིན་གྱི་གསུང་རྩོམ།
  author: ''
  volumes:
    664da3bf1a8744f08fb14f50ecf7644f:
      image_group_id: I1KG10349
      title: ''
      volume_number: 1
      total_pages: 384
      base_file: v001.txt
