id: I9B552E2B
legacy_id: P008214
ocr_import_info:
  bdrc_scan_id: W30388
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T20:43:22'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T11:35:33.182567+00:00'
last_modified: 2022-09-03 19:35:45.655943
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W30388
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW30388
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འགར་རྩེ་བསྟན་འཛིན་གྱི་གསུང་རྩོམ།
  author: འགར་རྩེ་བསྟན་འཛིན།
statistics:
  ocr_word_mean_confidence_index: 0.8879377258357717
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG10349:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10349
      total_pages: 384
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG10349.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8879377258357717
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
